# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: nrel/openstudio:2.4.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/btap

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            ~/.rbenv/shims/bundle install --jobs=4 --retry=3        
      

      # run tests!
      - run:
          name: run tests
          command: |
           ~/.rbenv/shims/bundle exec rake test:measure-tests

      # collect reports
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: timing/
          destination: test_timing_summary
